source 'https://github.com/CocoaPods/Specs.git'
swift_version = "5.0"
platform :ios, '16'
use_frameworks!

def my_pod_mbprogresshud
	# https://github.com/jdg/MBProgressHUD/commits/master
	pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :commit => 'c843e4c86d320a11552898646effa8000042ab16'
end

def my_pod_swiftybeaver
	# https://github.com/SwiftyBeaver/SwiftyBeaver/commits/master
	pod 'SwiftyBeaver', :git => 'https://github.com/SwiftyBeaver/SwiftyBeaver.git', :commit => 'dc3b9adf6c8faeb91a93b60993b5292d66b26c1c'
end

abstract_target 'BasePods' do
	my_pod_swiftybeaver

	target 'Tests' do
	end

	target 'TriangleDrawMain' do
		my_pod_mbprogresshud
	end

	target 'TriangleDrawThumbnail' do
	end

	target 'TriangleDrawLibrary' do
	end
end


# workaround: https://github.com/CocoaPods/CocoaPods/issues/7606
post_install do |installer|
	installer.pods_project.build_configurations.each do |config|
		config.build_settings.delete('CODE_SIGNING_ALLOWED')
		config.build_settings.delete('CODE_SIGNING_REQUIRED')
	end
end
