source 'https://github.com/CocoaPods/Specs.git'
swift_version = "5.0"
platform :ios, '11.3'
use_frameworks!

def my_pod_mbprogresshud
	# https://github.com/jdg/MBProgressHUD/commits/master
	pod 'MBProgressHUD', :git => 'https://github.com/jdg/MBProgressHUD.git', :commit => '61fb89ce30d42f403ce53cde65883dc8cea6d02a'
end

def my_pod_swiftybeaver
	# https://github.com/SwiftyBeaver/SwiftyBeaver/commits/master
	pod 'SwiftyBeaver', :git => 'https://github.com/SwiftyBeaver/SwiftyBeaver.git', :commit => 'e0fb3a74cb993d7dcf1e56734cdc98ad6e6d8176'
end

def my_pod_radiantforms
	# https://github.com/radiantkit/radiantforms-ios/commits/develop
	pod 'RadiantForms', :git => 'https://github.com/radiantkit/radiantforms-ios.git', :commit => 'd51a1380b783281f03fa3f5f1b5c34ba8e74400e'
end

abstract_target 'BasePods' do
	my_pod_swiftybeaver

	target 'Tests' do
	end

	target 'TriangleDrawMain' do
		my_pod_mbprogresshud
		my_pod_radiantforms
	end

	target 'TriangleDrawThumbnail' do
	end

	target 'TriangleDrawLibrary' do
	end
end


# workaround: https://github.com/CocoaPods/CocoaPods/issues/7606
post_install do |installer|
	installer.pods_project.build_configurations.each do |config|
		config.build_settings.delete('CODE_SIGNING_ALLOWED')
		config.build_settings.delete('CODE_SIGNING_REQUIRED')
	end
end
